dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.2.0

 


compiler:
  solc:
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.2.0"
  


deployed:
  SwappyGanacheCLI: "0x3194cBDC3dbcd3E11a07892e7bA5c3394048Cc87"
  ArbitrageQuickSwaptoApeswap: "0x9123C7B230cAEc803904a6C117fdd62F3B7184c2"
  ArbitrageSushitoApe: "0x10E026Fab87825870863aCac2381Cd82E9aB8B95"
  


networks:
    mainnet-fork:
        gas_limit: max
        gas_buffer: 1
        gas_price: 5
        reverting_tx_gas_limit: max
        default_contract_owner: true
    matic:
        gas_limit: max
        gas_buffer: 1
        gas_price: 5
        reverting_tx_gas_limit: max
        default_contract_owner: true

    