dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.2.0

 


compiler:
  solc:
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.2.0"
  


deployed:
  SwappyGanacheCLI: "0x3194cBDC3dbcd3E11a07892e7bA5c3394048Cc87"
  ArbitrageQuickSwaptoApeswap: "0x9123C7B230cAEc803904a6C117fdd62F3B7184c2"
  ArbitrageSushitoApe: "0x10E026Fab87825870863aCac2381Cd82E9aB8B95"
  ArbitrageQuicktoSushi: "0xd0c19561042bB17eF70d6EdbEF0d8d203FC03bE6"
  updatedArbitrageSushitoQuick: "0xf736F1c04A542F71A7C8D12C6A44efdA689385AD"
  ArbitrageApetoQuick: "0x4cFC1Bf2C3b64510C0347Bd8e51673EFBc11E927"
  ArbitrageApetoSushi: "0x14499c0983A3a188cf9C494C6366F7FA385D807e"
  RegularSwap: "0x374c3dFA10d61E36BbBBfb7759FBe88c93ef895d"
  


networks:
    mainnet-fork:
        gas_limit: max
        gas_buffer: 1
        gas_price: 5
        reverting_tx_gas_limit: max
        default_contract_owner: true
    matic:
        gas_limit: max
        gas_buffer: 10
        gas_price: 50
        reverting_tx_gas_limit: max
        default_contract_owner: true

    